### ISSUE TITLE
Cannot assign non-numeric values to 'var' with syntax as in Tutorial.cs.docx

### ISSUE THREAD

**Issue by burque505** [egonl/SharpDocx#73]
ISSUE: Running tutorial.exe from SampleProjects folder results in errors.
To reproduce, change <% var i = 1; %> to <% var i = "one"; %> in Tutorial.cs.docx.
Reverting to int instead of string removes the errors.

Errors:
`C:\Users\perplexed\Documents\repos\repos 2024\SharpDocx-master\Samples\SampleProjects\Tutorial\bin\Release\net6.0>tutorial.exe > ouch.txt
Unhandled exception. SharpDocx.SharpDocxCompilationException: Exception of type 'SharpDocx.SharpDocxCompilationException' was thrown.
   at SharpDocx.DocumentCompiler.Compile(String sourceCode, List`1 referencedAssemblies) in C:\Users\perplexed\Documents\repos\repos 2024\SharpDocx-master\SharpDocx\DocumentCompiler.cs:line 376
   at SharpDocx.DocumentCompiler.Compile(Stream viewStream, String className, String baseClassName, Type modelType, List`1 usingDirectives, List`1 referencedAssemblies) in C:\Users\perplexed\Documents\repos\repos 2024\SharpDocx-master\SharpDocx\DocumentCompiler.cs:line 152
   at SharpDocx.DocumentAssembly.Create(Stream viewStream, Type baseClass, Type modelType) in C:\Users\perplexed\Documents\repos\repos 2024\SharpDocx-master\SharpDocx\DocumentAssembly.cs:line 101
   at SharpDocx.DocumentAssembly..ctor(Stream viewStream, Type baseClass, Type modelType) in C:\Users\perplexed\Documents\repos\repos 2024\SharpDocx-master\SharpDocx\DocumentAssembly.cs:line 19
   at SharpDocx.DocumentFactory.CreateInternal(String viewId, Stream viewStream, Object model, Type baseClassType, Boolean forceCompile) in C:\Users\perplexed\Documents\repos\repos 2024\SharpDocx-master\SharpDocx\DocumentFactory.cs:line 165
   at SharpDocx.DocumentFactory.Create(String viewPath, Object model, Type baseClassType, Boolean forceCompile) in C:\Users\perplexed\Documents\repos\repos 2024\SharpDocx-master\SharpDocx\DocumentFactory.cs:line 118
   at Tutorial.Program.Main() in C:\Users\perplexed\Documents\repos\repos 2024\SharpDocx-master\Samples\SampleProjects\Tutorial\Program.cs:line 32`

Current version (2.5), Win10 Pro 64-bit, VS 17.9.4

**Comment by burque505** [comment]
This was my error. I declared a variable in Tutorial.cs.docx that was in conflict with other variables.
Apologies for the bonehead error.
